server:
  port: 8088


spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/gfo_shop?useUnicode=true&characterEncoding=utf-8&serverTimezone=Asia/Shanghai
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: root

    #redis配置
    #Redis服务器地址
  redis:
    host: 127.0.0.1
    #Redis服务器连接端口
    port: 6379
    #Redis数据库索引（默认为0）
    database: 0
    #连接池最大连接数（使用负值表示没有限制）
    jedis:
      pool:
        max-active: 50
    #连接池最大阻塞等待时间（使用负值表示没有限制）
        max-wait: 3000
    #连接池中的最大空闲连接
        max-idle: 20
    #连接池中的最小空闲连接
        min-idle: 2
    #连接超时时间（毫秒）
    timeout: 5000

  jackson:
    default-property-inclusion=non_null:
mybatis:
  mapper-locations: classpath*:mappers/*.xml

