server:
  port: 8088


spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/gfo_shop?useUnicode=true&characterEncoding=utf-8&serverTimezone=Asia/Shanghai
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: root
  jackson:
    default-property-inclusion=non_null:
mybatis:
  mapper-locations: classpath*:mappers/*.xml

